/**
 * Letter Types
 *
 * Semua tipe derive dari database.ts (generated by Supabase CLI).
 * Jangan hardcode string enum di sini — gunakan Enums<> helper.
 * Saat schema DB berubah, cukup jalankan: supabase gen types typescript
 */

import { Database, Enums, Tables, TablesInsert } from '@/types/database';
import type { StageType } from '@/types/workflow';

// ============================================
// ENUM TYPES — derive dari Database Enums, bukan hardcode
// ============================================

/** Status surat — sync otomatis dengan enum letter_status di Supabase */
export type LetterStatus = Enums<'letter_status'>;

/** Action type untuk history — sync otomatis dengan enum letter_action_type di Supabase */
export type LetterActionType = Enums<'letter_action_type'>;

// ============================================
// EXTENDED TYPES — Row + joined relations
// ============================================

/**
 * LetterHistory dengan joined user data dari Supabase select query.
 * `action_by` dan `assigned_to_user` adalah hasil join,
 * bukan kolom DB asli — jadi di-extend manual.
 */
export type LetterHistory = Tables<'letter_histories'> & {
  action_by?: Pick<Tables<'users'>, 'id' | 'nama' | 'email'>;
  assigned_to_user?: Pick<Tables<'users'>, 'id' | 'nama' | 'email'>;
};

/**
 * OutgoingLetter dengan semua relasi yang di-join via Supabase select.
 * Dipakai di detail page, revision page, dan approval page.
 */
export type OutgoingLetterWithRelations = Tables<'outgoing_letters'> & {
  document_type: Tables<'document_types'>;
  company: Tables<'instansi'>;
  created_by: Tables<'users'>;
  sender?: Tables<'users'> | null;
  histories?: LetterHistory[];
  workflow_stages?: Array<{
    id: number;
    stage_name: string;
    stage_type: string;
    sequence: number;
    assignee_users?: Array<Pick<Tables<'users'>, 'id' | 'nama' | 'email' | 'jabatan' | 'departemen'>>;
  }>;
};

// ============================================
// WORKFLOW TRACKING TYPE
// ============================================

/**
 * Representasi pending workflow tracking yang di-derive dari letter_histories.
 * to_status = null berarti masih pending (belum di-action).
 */
export type WorkflowTrackingFromHistory = {
  stage_type: StageType;
  sequence: number;
  assigned_to_id: string;
  status: string;
  notes: string | null;
  created_at: string;
  action_by?: Tables<'users'>;
};
