-- ============================================
-- COMPLETE LETTER WORKFLOW SETUP WITH USER CREATION FIX
-- ============================================
-- This file:
-- 1. Fixes auto-user creation trigger
-- 2. Creates all letter workflow tables
-- 3. Seeds document types
-- 4. Creates document number generator
-- 5. Creates test users and workflow configs
-- ============================================
-- Run via: https://supabase.com/dashboard/project/phfuwunwgzkfzettekkh/sql/new
-- ============================================

-- ============================================
-- PART 1: FIX USER CREATION TRIGGER
-- ============================================

-- Drop broken function
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;

-- Create fixed version with proper error handling
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  -- Check if profile already exists (don't duplicate)
  IF EXISTS (SELECT 1 FROM public.users WHERE id = NEW.id) THEN
    RETURN NEW;
  END IF;
  
  -- Insert new profile with fixed syntax
  INSERT INTO public.users (id, email, nama, username, nik, role, is_active)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(
      (NEW.raw_user_meta_data->>'nama'),
      COALESCE(NEW.raw_user_meta_data->>'full_name'),
      SPLIT_PART(NEW.email, '@', 1)
    ),
    COALESCE(
      (NEW.raw_user_meta_data->>'username'),
      SPLIT_PART(NEW.email, '@', 1)
    ),
    COALESCE(
      (NEW.raw_user_meta_data->>'nik'),
      'NIK-' || LEFT(NEW.id::TEXT, 8)
    ),
    COALESCE(
      (NEW.raw_user_meta_data->>'role')::user_role,
      'user'
    ),
    true
  )
  ON CONFLICT (id) DO NOTHING;
  
  RETURN NEW;
  
EXCEPTION
  WHEN OTHERS THEN
    -- Log error but don't block signup
    RAISE NOTICE 'Auto-create user profile failed (non-critical): %', SQLERRM;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Recreate trigger
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- ============================================
-- PART 2: CREATE LETTER WORKFLOW TABLES
-- ============================================

-- Document Types Table
CREATE TABLE IF NOT EXISTS document_types (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Document Workflow Configs Table
CREATE TABLE IF NOT EXISTS document_workflow_configs (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_type_id INT NOT NULL REFERENCES document_types(id) ON DELETE CASCADE,
  stage_type TEXT NOT NULL CHECK (stage_type IN ('REVIEW', 'APPROVAL')),
  sequence INT NOT NULL,
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  review_mode TEXT CHECK (review_mode IN ('SEQUENTIAL', 'PARALLEL')),
  completion_rule TEXT CHECK (completion_rule IN ('ALL', 'ANY')),
  is_required BOOLEAN DEFAULT true,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(document_type_id, stage_type, sequence, user_id)
);

-- Outgoing Letters Table
CREATE TABLE IF NOT EXISTS outgoing_letters (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  document_type_id INT NOT NULL REFERENCES document_types(id) ON DELETE CASCADE,
  company_id UUID REFERENCES instansi(id) ON DELETE SET NULL,
  letter_date DATE NOT NULL,
  document_number TEXT UNIQUE,
  subject TEXT NOT NULL,
  opening TEXT,
  body TEXT,
  closing TEXT,
  recipient_company TEXT NOT NULL,
  recipient_name TEXT NOT NULL,
  recipient_whatsapp TEXT NOT NULL,
  recipient_email TEXT,
  recipient_address TEXT,
  sender_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  sender_name TEXT,
  sender_email TEXT,
  sender_department TEXT,
  status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'SUBMITTED_TO_REVIEW', 'NEEDS_REVISION', 'REVIEWED', 'APPROVED', 'REJECTED')),
  has_attachments BOOLEAN DEFAULT false,
  attachments JSONB,
  signatories JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by_id UUID REFERENCES public.users(id) ON DELETE SET NULL
);

-- Letter Workflow Trackings Table
CREATE TABLE IF NOT EXISTS letter_workflow_trackings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  letter_id UUID NOT NULL REFERENCES outgoing_letters(id) ON DELETE CASCADE,
  stage_type TEXT NOT NULL CHECK (stage_type IN ('REVIEW', 'APPROVAL')),
  sequence INT NOT NULL,
  assigned_to_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'REQUESTED_REVISION')),
  notes TEXT,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(letter_id, assigned_to_id)
);

-- Letter Histories Table
CREATE TABLE IF NOT EXISTS letter_histories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  letter_id UUID NOT NULL REFERENCES outgoing_letters(id) ON DELETE CASCADE,
  action_by_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  action_type TEXT NOT NULL CHECK (action_type IN ('CREATED', 'SUBMITTED', 'APPROVED_REVIEW', 'REQUESTED_REVISION', 'REVISED', 'APPROVED_FINAL', 'REJECTED')),
  from_status TEXT,
  to_status TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- PART 3: SEED DOCUMENT TYPES
-- ============================================

INSERT INTO document_types (code, name, description, category, is_active, created_at, updated_at)
VALUES
  ('SPH', 'Surat Penawaran Harga', 'Dokumen penawaran harga untuk proyek atau pekerjaan', 'Commercial', true, NOW(), NOW()),
  ('PO', 'Purchase Order', 'Dokumen pemesanan barang atau jasa ke vendor', 'Commercial', true, NOW(), NOW()),
  ('INV', 'Invoice', 'Dokumen tagihan pembayaran kepada klien', 'Commercial', true, NOW(), NOW()),
  ('SKT', 'Surat Kontrak', 'Dokumen kontrak kerjasama atau perjanjian', 'Legal', true, NOW(), NOW()),
  ('MOU', 'Memorandum of Understanding', 'Dokumen kesepakatan awal kerjasama', 'Legal', true, NOW(), NOW()),
  ('MEMO', 'Memo Internal', 'Dokumen komunikasi internal antar departemen', 'Internal', true, NOW(), NOW()),
  ('EDM', 'Edaran', 'Dokumen pengumuman atau instruksi resmi', 'Internal', true, NOW(), NOW()),
  ('SPK', 'Surat Perintah Kerja', 'Dokumen instruksi pelaksanaan pekerjaan', 'Operation', true, NOW(), NOW()),
  ('SR', 'Surat Referensi', 'Dokumen referensi atau rekomendasi', 'Support', true, NOW(), NOW())
ON CONFLICT (code) DO NOTHING;

-- ============================================
-- PART 4: CREATE TEST USERS (via auth)
-- ============================================

-- NOTE: Users will be created via Supabase Dashboard
-- After creating them, run the workflow config setup below

-- For now, let's create a function to set up workflow configs once users exist

-- ============================================
-- PART 5: CREATE DOCUMENT NUMBER FUNCTION
-- ============================================

CREATE OR REPLACE FUNCTION generate_test_document_number()
RETURNS TEXT AS $$
DECLARE
  v_counter INT;
  v_number TEXT;
BEGIN
  -- Simple counter from sequence
  SELECT COALESCE(MAX(id), 0) INTO v_counter 
  FROM outgoing_letters 
  WHERE document_number IS NOT NULL;
  
  v_number := 'TEST-' || (v_counter + 1)::TEXT;
  
  RETURN v_number;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- PART 6: WORKFLOW CONFIG SETUP FUNCTION
-- ============================================

-- Function to create workflow configs for all document types
CREATE OR REPLACE FUNCTION setup_letter_workflow_configs()
RETURNS VOID AS $$
DECLARE
  v_doc_type_id INT;
  v_reviewer1_id UUID;
  v_reviewer2_id UUID;
  v_approver1_id UUID;
BEGIN
  -- Get user IDs
  SELECT id INTO v_reviewer1_id FROM public.users WHERE email = 'reviewer1@test.com';
  SELECT id INTO v_reviewer2_id FROM public.users WHERE email = 'reviewer2@test.com';
  SELECT id INTO v_approver1_id FROM public.users WHERE email = 'approver@test.com';
  
  -- If users don't exist yet, skip
  IF v_reviewer1_id IS NULL OR v_reviewer2_id IS NULL OR v_approver1_id IS NULL THEN
    RAISE NOTICE 'Test users not found. Please create reviewer1@test.com, reviewer2@test.com, and approver@test.com first.';
    RETURN;
  END IF;
  
  -- For each document type, create workflow config
  FOR v_doc_type_id IN 
    (SELECT id FROM document_types WHERE code IN ('SPH', 'PO', 'INV', 'SKT', 'MOU', 'MEMO', 'EDM', 'SPK', 'SR'))
  LOOP
    INSERT INTO document_workflow_configs 
    (document_type_id, stage_type, sequence, user_id, review_mode, completion_rule, is_required, is_active, created_at, updated_at)
    VALUES
      (v_doc_type_id, 'REVIEW', 1, v_reviewer1_id, 'PARALLEL', 'ALL', true, true, NOW(), NOW()),
      (v_doc_type_id, 'REVIEW', 1, v_reviewer2_id, 'PARALLEL', 'ALL', true, true, NOW(), NOW()),
      (v_doc_type_id, 'APPROVAL', 2, v_approver1_id, NULL, NULL, true, true, NOW(), NOW())
    ON CONFLICT (document_type_id, stage_type, sequence, user_id) DO NOTHING;
  END LOOP;
  
  RAISE NOTICE 'Workflow configs created successfully!';
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- PART 7: VERIFICATION QUERIES
-- ============================================

-- Check document types
SELECT 
  id,
  code,
  name,
  category
FROM document_types
ORDER BY category, name;

-- Check tables exist
SELECT 
  schemaname,
  tablename 
FROM pg_tables 
WHERE schemaname = 'public' 
  AND tablename IN (
    'document_types',
    'document_workflow_configs',
    'outgoing_letters',
    'letter_workflow_trackings',
    'letter_histories'
  );

-- Test document number function
SELECT generate_test_document_number() as test_number;

-- ============================================
-- NEXT STEPS
-- ============================================
-- 1. Run this SQL file to:
--    - Fix user auto-creation trigger
--    - Create all letter workflow tables
--    - Seed document types
--    - Create document number function
-- 
-- 2. Create test users via Supabase Dashboard > Authentication:
--    - reviewer1@test.com (password: password123)
--    - reviewer2@test.com (password: password123)
--    - approver@test.com (password: password123)
-- 
-- 3. Run workflow config setup:
--    SELECT setup_letter_workflow_configs();
-- 
-- 4. Verify everything works:
--    SELECT dt.code as doc_type, dwc.stage_type, u.username as assigned_to
--    FROM document_workflow_configs dwc
--    JOIN document_types dt ON dwc.document_type_id = dt.id
--    JOIN users u ON dwc.user_id = u.id
--    ORDER BY dt.code, dwc.sequence;
-- ============================================