-- ============================================
-- LETTER WORKFLOW COMPLETE SETUP
-- ============================================
-- This file combines all 4 migrations for letter workflow
-- Safe to run multiple times (uses IF NOT EXISTS)
-- Run via: https://supabase.com/dashboard/project/phfuwunwgzkfzettekkh/sql/new
-- ============================================

-- ============================================
-- PART 1: CREATE TABLES (if not exist)
-- ============================================

-- Document Types Table
CREATE TABLE IF NOT EXISTS document_types (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Document Workflow Configs Table
CREATE TABLE IF NOT EXISTS document_workflow_configs (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_type_id INT NOT NULL REFERENCES document_types(id) ON DELETE CASCADE,
  stage_type TEXT NOT NULL CHECK (stage_type IN ('REVIEW', 'APPROVAL')),
  sequence INT NOT NULL,
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  review_mode TEXT CHECK (review_mode IN ('SEQUENTIAL', 'PARALLEL')),
  completion_rule TEXT CHECK (completion_rule IN ('ALL', 'ANY')),
  is_required BOOLEAN DEFAULT true,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(document_type_id, stage_type, sequence, user_id)
);

-- Outgoing Letters Table
CREATE TABLE IF NOT EXISTS outgoing_letters (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  document_type_id INT NOT NULL REFERENCES document_types(id) ON DELETE CASCADE,
  company_id UUID REFERENCES instansi(id) ON DELETE SET NULL,
  letter_date DATE NOT NULL,
  document_number TEXT UNIQUE,
  subject TEXT NOT NULL,
  opening TEXT,
  body TEXT,
  closing TEXT,
  recipient_company TEXT NOT NULL,
  recipient_name TEXT NOT NULL,
  recipient_whatsapp TEXT NOT NULL,
  recipient_email TEXT,
  recipient_address TEXT,
  sender_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  sender_name TEXT,
  sender_email TEXT,
  sender_department TEXT,
  status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'SUBMITTED_TO_REVIEW', 'NEEDS_REVISION', 'REVIEWED', 'APPROVED', 'REJECTED')),
  has_attachments BOOLEAN DEFAULT false,
  attachments JSONB,
  signatories JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by_id UUID REFERENCES public.users(id) ON DELETE SET NULL
);

-- Letter Workflow Trackings Table
CREATE TABLE IF NOT EXISTS letter_workflow_trackings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  letter_id UUID NOT NULL REFERENCES outgoing_letters(id) ON DELETE CASCADE,
  stage_type TEXT NOT NULL CHECK (stage_type IN ('REVIEW', 'APPROVAL')),
  sequence INT NOT NULL,
  assigned_to_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'REQUESTED_REVISION')),
  notes TEXT,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(letter_id, assigned_to_id)
);

-- Letter Histories Table
CREATE TABLE IF NOT EXISTS letter_histories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  letter_id UUID NOT NULL REFERENCES outgoing_letters(id) ON DELETE CASCADE,
  action_by_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  action_type TEXT NOT NULL CHECK (action_type IN ('CREATED', 'SUBMITTED', 'APPROVED_REVIEW', 'REQUESTED_REVISION', 'REVISED', 'APPROVED_FINAL', 'REJECTED')),
  from_status TEXT,
  to_status TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- PART 2: SEED DOCUMENT TYPES
-- ============================================

INSERT INTO document_types (code, name, description, category, is_active, created_at, updated_at)
VALUES
  ('SPH', 'Surat Penawaran Harga', 'Dokumen penawaran harga untuk proyek atau pekerjaan', 'Commercial', true, NOW(), NOW()),
  ('PO', 'Purchase Order', 'Dokumen pemesanan barang atau jasa ke vendor', 'Commercial', true, NOW(), NOW()),
  ('INV', 'Invoice', 'Dokumen tagihan pembayaran kepada klien', 'Commercial', true, NOW(), NOW()),
  ('SKT', 'Surat Kontrak', 'Dokumen kontrak kerjasama atau perjanjian', 'Legal', true, NOW(), NOW()),
  ('MOU', 'Memorandum of Understanding', 'Dokumen kesepakatan awal kerjasama', 'Legal', true, NOW(), NOW()),
  ('MEMO', 'Memo Internal', 'Dokumen komunikasi internal antar departemen', 'Internal', true, NOW(), NOW()),
  ('EDM', 'Edaran', 'Dokumen pengumuman atau instruksi resmi', 'Internal', true, NOW(), NOW()),
  ('SPK', 'Surat Perintah Kerja', 'Dokumen instruksi pelaksanaan pekerjaan', 'Operation', true, NOW(), NOW()),
  ('SR', 'Surat Referensi', 'Dokumen referensi atau rekomendasi', 'Support', true, NOW(), NOW())
ON CONFLICT (code) DO NOTHING;

-- ============================================
-- PART 3: CREATE TEST USERS (if not exist)
-- ============================================

-- Check if users already exist, use their IDs
-- If not, we'll need you to create them via auth first

-- For now, let's just create workflow configs assuming users exist
-- You can update the user IDs later

-- ============================================
-- PART 4: SEED WORKFLOW CONFIGS
-- ============================================

-- Use your actual reviewer and approver user IDs
-- Replace these UUIDs with your actual user IDs from auth.users table

-- For now, let's use placeholder - you'll need to create users first
-- Run this AFTER creating users via Supabase Dashboard > Authentication

-- Example workflow config (update user IDs):
DO $$
DECLARE
  v_doc_type_id INT;
  v_reviewer1_id UUID := NULL; -- Replace with actual UUID from auth.users
  v_reviewer2_id UUID := NULL; -- Replace with actual UUID from auth.users
  v_approver1_id UUID := NULL;  -- Replace with actual UUID from auth.users
BEGIN
  IF v_reviewer1_id IS NOT NULL AND v_reviewer2_id IS NOT NULL AND v_approver1_id IS NOT NULL THEN
    -- For each document type, create workflow config
    FOR v_doc_type_id IN 
      (SELECT id FROM document_types WHERE code IN ('SPH', 'PO', 'INV', 'SKT', 'MOU', 'MEMO', 'EDM', 'SPK', 'SR'))
    LOOP
      INSERT INTO document_workflow_configs 
      (document_type_id, stage_type, sequence, user_id, review_mode, completion_rule, is_required, is_active, created_at, updated_at)
      VALUES
        (v_doc_type_id, 'REVIEW', 1, v_reviewer1_id, 'PARALLEL', 'ALL', true, true, NOW(), NOW()),
        (v_doc_type_id, 'REVIEW', 1, v_reviewer2_id, 'PARALLEL', 'ALL', true, true, NOW(), NOW()),
        (v_doc_type_id, 'APPROVAL', 2, v_approver1_id, NULL, NULL, true, true, NOW(), NOW())
      ON CONFLICT (document_type_id, stage_type, sequence, user_id) DO NOTHING;
    END LOOP;
  END IF;
END $$;

-- ============================================
-- PART 5: CREATE DOCUMENT NUMBER FUNCTION
-- ============================================

CREATE OR REPLACE FUNCTION generate_test_document_number()
RETURNS TEXT AS $$
DECLARE
  v_counter INT;
  v_number TEXT;
BEGIN
  -- Simple counter from sequence
  SELECT COALESCE(MAX(id), 0) INTO v_counter 
  FROM outgoing_letters 
  WHERE document_number IS NOT NULL;
  
  v_number := 'TEST-' || (v_counter + 1)::TEXT;
  
  RETURN v_number;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- PART 6: VERIFICATION QUERIES
-- ============================================

-- Check document types
SELECT 
  id,
  code,
  name,
  category
FROM document_types
ORDER BY category, name;

-- Check tables exist
SELECT 
  schemaname,
  tablename 
FROM pg_tables 
WHERE schemaname = 'public' 
  AND tablename IN (
    'document_types',
    'document_workflow_configs',
    'outgoing_letters',
    'letter_workflow_trackings',
    'letter_histories'
  );

-- Test document number function
SELECT generate_test_document_number() as test_number;

-- ============================================
-- NEXT STEPS
-- ============================================
-- 1. Create users via Supabase Dashboard > Authentication
--    - reviewer1@test.com (password: password123)
--    - reviewer2@test.com (password: password123)
--    - approver@test.com (password: password123)
-- 
-- 2. Get their UUIDs from auth.users table
--
-- 3. Update workflow configs with actual user IDs:
--    UPDATE document_workflow_configs
--    SET user_id = 'actual-user-uuid-here'
--    WHERE stage_type = 'REVIEW' AND sequence = 1 AND id = 1;
-- 
-- 4. Create public.users profiles for auth users
-- ============================================